version: "3.3"

services:

  data1:
    image: mongo:4.0
    ports:
      - 17017:27017
    networks:
      - mongo
    volumes:
      - data:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.name == data1

  data2:
    image: mongo:4.0
    ports:
      - 27017:27017
    networks:
      - mongo
    volumes:
      - data:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.name == data2

  data3:
    image: mongo:4.0
    ports:
      - 37017:27017
    networks:
      - mongo
    volumes:
      - data:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.name == data3

networks:
  mongo:

volumes:
    data: {}

